on: push
name: Build Test Deploy
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with: 
        go-version: '1.16'
    - run: go test ./... 
  docker-build:
    needs: go-test
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: humbertoe10/pokeapi:${{ github.sha }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  aws-deploy:
    needs: docker-build
    name: Deploy new release
    runs-on: ubuntu-latest
    steps:
      - name: Deploy new docker image
        uses: tuongaz/kubctl-eks-action@1.0.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_BASE_64_ENCODED }}
          DOCKER_TAG: ${{ github.sha }}
        with:
          args: set image deployment/api-deployment pokeapi=docker.io/humbertoe10/pokeapi:$DOCKER_TAG